version: 0.1
phases:
    pre_build:
        commands:
            - docker build -t projectweekend/aws-codepipeline-test .
    build:
        commands:
            - docker run projectweekend/aws-codepipeline-test pytest
